# Generated by Django 3.2 on 2021-08-06 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornada',
            name='fk_servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='namp.servidor', verbose_name='Servidor'),
        ),
    ]
