# Generated by Django 3.2 on 2021-07-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='categoria',
            field=models.CharField(choices=[('PLANTAO', 'Plantão'), ('EXPEDIENTE', 'Expediente')], max_length=10, verbose_name='Categoria'),
        ),
    ]
