# Generated by Django 3.2 on 2021-07-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0002_alter_equipe_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='categoria',
            field=models.CharField(choices=[('Plantão', 'Plantão'), ('Expediente', 'Expediente')], max_length=10, verbose_name='Categoria'),
        ),
    ]
